version: "3.8"
services:
  db:
    image: mariadb:10.3
    container_name: unigo-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: unigo
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3333:3306"
    volumes:
      - dbdata:/var/lib/mysql/data
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: unigo-pmy
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - 8033:80
    depends_on:
      - db
volumes:
  dbdata:
