server:
  port: 8080
  servlet:
    context-path: "/unigo"

spring:
  application:
    name: unigo
  datasource:
    url: jdbc:mariadb://localhost:3333/unigo?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

jwt:
  secret: ${JWT_SECRET:'2f5626185baf25cf286a0d831255970395de10fd29122a2bed6df10ea591f382W'}
  expiration: 86400000